name: Java CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 21 ]
        distro: [ oracle ]
    name: Java ${{matrix.java}}
    steps:
    - uses: actions/checkout@v5
    - name: Set up java
      uses: actions/setup-java@v4
      with:
        distribution: ${{matrix.distro}}
        java-version: ${{matrix.java}}
    - name: Build with Maven
      run: mvn -B verify --file pom.xml -Dgpg.skip
